export const MARK_AS_FAVORITE_REQUEST = 'MARK_AS_FAVORITE_REQUEST' as const
export const MARK_AS_FAVORITE_SUCCESS = 'MARK_AS_FAVORITE_SUCCESS' as const
export const MARK_AS_FAVORITE_FAILURE = 'MARK_AS_FAVORITE_FAILURE' as const

export const GET_FAVORITE_REQUEST = 'GET_FAVORITE_REQUEST' as const
export const GET_FAVORITE_SUCCESS = 'GET_FAVORITE_SUCCESS' as const
export const GET_FAVORITE_FAILURE = 'GET_FAVORITE_FAILURE' as const
