export const MARK_AS_PURCHASED_REQUEST = 'MARK_AS_PURCHASED_REQUEST' as const
export const MARK_AS_PURCHASED_SUCCESS = 'MARK_AS_PURCHASED_SUCCESS' as const
export const MARK_AS_PURCHASED_FAILURE = 'MARK_AS_PURCHASED_FAILURE' as const

export const GET_PURCHASED_REQUEST = 'GET_PURCHASED_REQUEST' as const
export const GET_PURCHASED_SUCCESS = 'GET_PURCHASED_SUCCESS' as const
export const GET_PURCHASED_FAILURE = 'GET_PURCHASED_FAILURE' as const
