export const USER_AUTH_TOKEN_REQUEST = 'USER_AUTH_TOKEN_REQUEST' as const
export const USER_AUTH_TOKEN_SUCCESS = 'USER_AUTH_TOKEN_SUCCESS' as const
export const USER_AUTH_TOKEN_FAILURE = 'USER_AUTH_TOKEN_FAILURE' as const

export const USER_AUTH_VALIDATE_TOKEN_REQUEST = 'USER_AUTH_VALIDATE_TOKEN_REQUEST' as const
export const USER_AUTH_VALIDATE_TOKEN_SUCCESS = 'USER_AUTH_VALIDATE_TOKEN_SUCCESS' as const
export const USER_AUTH_VALIDATE_TOKEN_FAILURE = 'USER_AUTH_VALIDATE_TOKEN_FAILURE' as const

export const USER_AUTH_SESSION_ID_REQUEST = 'USER_AUTH_SESSION_ID_REQUEST' as const
export const USER_AUTH_SESSION_ID_SUCCESS = 'USER_AUTH_SESSION_ID_SUCCESS' as const
export const USER_AUTH_SESSION_ID_FAILURE = 'USER_AUTH_SESSION_ID_FAILURE' as const
